# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "6dfcfbf103db17e0b1a4ca86c492e854"
application_url = "https://vietnam-fiber-restricted-climbing.trycloudflare.com"
embedded = true
name = "gridpop"
handle = "gridpop"

[webhooks]
api_version = "2025-01"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://vietnam-fiber-restricted-climbing.trycloudflare.com/auth/callback",
  "https://vietnam-fiber-restricted-climbing.trycloudflare.com/auth/shopify/callback",
  "https://vietnam-fiber-restricted-climbing.trycloudflare.com/api/auth/callback"
]

[pos]
embedded = false

[build]
dev_store_url = "test-store-xo12.myshopify.com"
automatically_update_urls_on_dev = true
include_config_on_deploy = true
